<div class="px-4 md:px-0 md:w-[80%] 2xl:w-[70%] mt-30 md:mx-auto selection:bg-[#05426F] selection:text-white">
    <div>
        <span class="text-2xl flex items-center justify-center font-bold">Tentang Desa</span>
            <p class="text-justify">Desa Sumberjaya merupakan salah satu desa yang berada di Kecamatan Sumur, Kabupaten Pandeglang, Provinsi Banten. Secara geografis, desa ini terletak di pesisir barat Pulau Jawa dan berbatasan langsung dengan Laut Selat Sunda di sebelah utara. Karena posisinya yang strategis, Desa Sumberjaya dikenal dengan sebutan “Serambi Ujung Kulon”, yang menandai perannya sebagai pintu masuk menuju kawasan konservasi Taman Nasional Ujung Kulon—salah satu situs warisan dunia yang memiliki nilai ekologis tinggi. Desa ini terbentuk secara administratif pada tahun 1988 setelah pemekaran dari Desa Cigorondong seiring dengan pembentukan Kecamatan Sumur, dan terus berkembang menjadi desa swakarya yang berciri pesisir dan nelayan.
            Sebagai desa dengan total penduduk 4.369 jiwa dan komposisi pekerjaan yang didominasi oleh nelayan (776 orang) serta petani (137 orang), Sumberjaya memiliki kekayaan sumber daya alam yang sangat potensial. Komoditas unggulan desa meliputi hasil perikanan laut seperti udang dan ikan karamba, pertanian padi sawah dengan hasil produksi mencapai 36 ton per hektar, serta berbagai jenis hasil perkebunan dan peternakan rakyat. Selain itu, keberadaan pantai sepanjang ±3,5 hektar yang aktif digunakan sebagai wisata bahari menjadi daya tarik tersendiri untuk pengembangan sektor pariwisata dan ekonomi kreatif. Dalam upaya mewujudkan visi desa yaitu “Kebersamaan dalam membangun demi Desa Sumberjaya yang lebih maju”, pemerintah desa bersama masyarakat terus mendorong program pembangunan yang partisipatif, pelayanan publik yang optimal, serta pemberdayaan masyarakat melalui lembaga desa seperti BUMDes, Karang Taruna, dan TP PKK.
            Infrastruktur dasar di Desa Sumberjaya juga terus dibenahi untuk menunjang aktivitas masyarakat dan mendukung sektor ekonomi serta pariwisata. Jalan desa sepanjang 3 kilometer telah diaspal, ditambah 4 kilometer jalan kabupaten yang menghubungkan desa dengan pusat kecamatan dan kabupaten. Sarana pendidikan meliputi dua unit SD dan dua unit TK, sementara untuk pendidikan tingkat menengah dan atas masih harus diakses dari desa tetangga. Di bidang kesehatan, desa memiliki satu unit Puskesmas dan lima Posyandu aktif. Ketersediaan air bersih cukup memadai dengan 50 sumur gali dan 25 sumur pompa. Di sisi lain, keberadaan dua masjid dan sembilan mushola menjadi pusat kegiatan keagamaan masyarakat yang mayoritas beragama Islam dan berasal dari etnis Sunda. Dengan segala potensi dan keunggulan yang dimiliki, Desa Sumberjaya terus berbenah sebagai desa pesisir yang adaptif, berdaya saing, dan menjadi representasi kawasan penyangga Ujung Kulon yang berkelanjutan.
        </p>
    </div>
</div>
